apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: crossplane-ec2-demo
spec:
  forProvider:
    region: us-east-1
    instanceType: t3.micro
    ami: ami-0c02fb55956c7d316   # us-east-1 Amazon Linux 2 AMI
    subnetId: subnet-02ee6e6c8b19a3a7b     # <- replace with subnet from step 2
    vpcSecurityGroupIds:
      - sg-07301df0de2f8f5c9               # <- replace with SG from step 2
    tags:
      Name: crossplane-ec2-demo
  providerConfigRef:
    name: aws-provider
